FROM --platform=$BUILDPLATFORM golang:1.26@sha256:e30143be198ab04cf7ba25fba83ab3a692ca584c994aad0bf131fa0eb32dd8c1 AS builder
ARG TARGETOS
ARG TARGETARCH
WORKDIR /build/
COPY cmd ./cmd
COPY backend.go .
COPY signer.go .
COPY user.go .
COPY Makefile .
COPY go.mod .
COPY go.sum .
RUN make build GOOS=${TARGETOS} GOARCH=${TARGETARCH}

FROM hashicorp/vault:1.21.4@sha256:4e33b126a59c0c333b76fb4e894722462659a6bec7c48c9ee8cea56fccfd2569
COPY --from=builder /build/vault/plugins/spiral-safe /vault/plugins/spiral-safe
# COPY start.sh .
EXPOSE 8200
COPY Makefile .
ENTRYPOINT sh -c "vault server -dev -dev-root-token-id=root -dev-plugin-dir=./vault/plugins & sleep 2 ; VAULT_ADDR='http://127.0.0.1:8200' vault secrets enable -path=spiral-safe spiral-safe & wait"
