apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spiral-safe
resources:
  - namespace.yaml
  - service-account.yaml
  - service.yaml
  - client.yaml
  - pdb.yaml
labels:
  - pairs:
      app.kubernetes.io/managed-by: skaffold
