apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: spiral-service
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spiral-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: spiral-client
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spiral-client
