apiVersion: v1
kind: ServiceAccount
metadata:
  name: spiral-service
  labels:
    app.kubernetes.io/name: spiral-service
    app.kubernetes.io/part-of: spiral-safe
automountServiceAccountToken: true
